---
# tasks file for installing prerequisites
- name: Install Docker
  ansible.builtin.package:
    name: docker
    state: present

- name: Install pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install Docker Compose
  ansible.builtin.shell:
    cmd: /usr/bin/pip3 install docker-compose