---
- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker's official repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Create graylog user
  user:
    name: graylog
    state: present

- name: Add graylog user to docker group
  user:
    name: graylog
    groups: docker
    append: yes

- name: Ensure /opt/graylog directory exists
  file:
    path: /opt/graylog
    state: directory
    owner: graylog
    group: graylog
    mode: '0755'