---
# APT Configuration
- name: Configure local APT repositories
  include_tasks: apt.yaml

---
- name: Configure login notification
  hosts: all
  tasks:
    - name: Create login notification script
      copy:
        dest: /usr/local/bin/login_notify.sh
        mode: 0755
        content: |
          #!/bin/bash
          curl -H tags:yellow_circle -H "Title: Login: \"$USER\"" -d "Logged into \"`hostname -f`\" at `date`" ntfy.sh/CDMKY-Login > /dev/null 2>&1

    - name: Configure PAM to run the script at login
      lineinfile:
        path: /etc/pam.d/sshd
        line: 'session    optional     pam_exec.so /usr/local/bin/login_notify.sh'
        state: present