- name: Gather facts about wazuh-agent service
  ansible.builtin.service_facts:

- name: Check if .deb file exists
  ansible.builtin.stat:
    path: /tmp/wazuh-agent_4.7.3-1_amd64.deb
  register: deb_file
  when: "'wazuh-agent' not in ansible_facts.services or ansible_facts.services['wazuh-agent'].state != 'running'"

- name: Download Wazuh Agent
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.3-1_amd64.deb
    dest: /tmp/wazuh-agent_4.7.3-1_amd64.deb
  when: not deb_file.stat.exists and "'wazuh-agent' not in ansible_facts.services or ansible_facts.services['wazuh-agent'].state != 'running'"

- name: Install Wazuh Agent
  ansible.builtin.apt:
    deb: /tmp/wazuh-agent_4.7.3-1_amd64.deb
  environment:
    WAZUH_MANAGER: "siem.east.codemonkey.science"
    WAZUH_AGENT_NAME: "{{ ansible_fqdn }}"
  when: "'wazuh-agent' not in ansible_facts.services or ansible_facts.services['wazuh-agent'].state != 'running'"

- name: Remove .deb file
  ansible.builtin.file:
    path: /tmp/wazuh-agent_4.7.3-1_amd64.deb
    state: absent
  when: deb_file.stat.exists

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes
  when: "'wazuh-agent' not in ansible_facts.services or ansible_facts.services['wazuh-agent'].state != 'running'"

- name: Enable and start wazuh-agent service
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: yes
    state: started
  when: "'wazuh-agent' not in ansible_facts.services or ansible_facts.services['wazuh-agent'].state != 'running'"