---
- name: Check if .deb file exists
  ansible.builtin.stat:
    path: /tmp/wazuh-agent_4.7.3-1_amd64.deb
  register: deb_file

- name: Download Wazuh Agent
  ansible.builtin.get_url:
    url: https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.7.3-1_amd64.deb
    dest: /tmp/wazuh-agent_4.7.3-1_amd64.deb
  when: not deb_file.stat.exists

- name: Install Wazuh Agent
  ansible.builtin.apt:
    deb: /tmp/wazuh-agent_4.7.3-1_amd64.deb
  environment:
    WAZUH_MANAGER: "siem.east.codemonkey.science"
    WAZUH_AGENT_NAME: "{{ ansible_fqdn }}"

- name: Remove .deb file
  ansible.builtin.file:
    path: /tmp/wazuh-agent_4.7.3-1_amd64.deb
    state: absent

- name: Reload systemd manager configuration
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start wazuh-agent service
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: yes
    state: started