- name: Gather facts about wazuh-agent service
  ansible.builtin.service_facts:

- name: End playbook if wazuh-agent service is already running
  meta: end_play
  when: "'wazuh-agent' in ansible_facts.services and ansible_facts.services['wazuh-agent'].state == 'running'"

- name: Check if Wazuh GPG key is imported
  ansible.builtin.shell:
    cmd: gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --list-keys 9B3EE5F29111145 || true
  register: gpg_key_check
  changed_when: "'error reading key: No public key' in gpg_key_check.stderr"

- name: Import Wazuh GPG key
  ansible.builtin.shell:
    cmd: |
      curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import
      chmod 644 /usr/share/keyrings/wazuh.gpg
  when: gpg_key_check.rc != 0

- name: Add Wazuh repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main
    state: present

- name: Update apt and install Wazuh agent
  ansible.builtin.apt:
    name: wazuh-agent
    update_cache: yes
    state: present

- name: Register the Wazuh agent
  ansible.builtin.command:
    cmd: /var/ossec/bin/agent-auth -m siem.east.codemonkey.science -A "{{ ansible_fqdn }}"

- name: Enable and start wazuh-agent service
  ansible.builtin.systemd:
    name: wazuh-agent
    enabled: yes
    state: started