---

- hosts: pve1.east.codemonkey.science, pve2.east.codemonkey.science
  become: yes
  roles:
  - proxmox

- hosts: production, proxmox
  become: yes
  roles:
  - common
  - lab

- hosts: siem.east.codemonkey.science
  become: yes
  roles:
#  - wazuh
  - ubuntu

- hosts: sim.east.codemonkey.science
  become: yes
  roles:
#  - graylog
  - ubuntu

- hosts: auth.east.codemonkey.science
  become: yes
  roles:
#  - authentik
  - ubuntu

- hosts: cti.east.codemonkey.science
  become: yes
  roles:
  - opencti
  - ubuntu

- hosts: misp.east.codemonkey.science
  become: yes
  roles:
  - misp
  - ubuntu

- hosts: status.east.codemonkey.science
  become: yes
  roles:
#  - uptime-kuma
  - ubuntu

- hosts: production, proxmox
  become: yes
  roles:
#  - wazuh-agent
  - graylog-forwarder