---
- name: Update apt cache
  become: true
  become_user: root
  apt:
    update_cache: yes

- name: Restart unattended-upgrades
  become: true
  become_user: root
  service:
    name: unattended-upgrades
    state: restarted